name: Backend CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ACR Login
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build & Push Product Service
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/product_service:${{ github.sha }} backend/product_service
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/product_service:${{ github.sha }}

      - name: Build & Push Order Service
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/order_service:${{ github.sha }} backend/order_service
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/order_service:${{ github.sha }}

      - name: Set kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" > $HOME/kubeconfig
          export KUBECONFIG=$HOME/kubeconfig
          kubectl config view --minify --flatten

      - name: Deploy manifests
        run: |
          export KUBECONFIG=$HOME/kubeconfig
          kubectl apply -f k8s/product-service.yaml -n w08-aks
          kubectl apply -f k8s/order-service.yaml -n w08-aks
