name: Backend CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies for Product Service
        run: pip install -r backend/product_service/requirements.txt

      - name: Run tests for Product Service
        run: pytest backend/product_service/tests || echo "No tests for product_service"

      - name: Install dependencies for Order Service
        run: pip install -r backend/order_service/requirements.txt

      - name: Run tests for Order Service
        run: pytest backend/order_service/tests || echo "No tests for order_service"