name: Frontend CI - Build and Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # 登录 Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 构建并推送 Frontend 镜像（写死 registry 名字）
    - name: Build and Push Frontend Image
      run: |
        docker build -t sit722devopszzjacr.azurecr.io/frontend:latest ./frontend/
        docker push sit722devopszzjacr.azurecr.io/frontend:latest

    - name: Logout from Azure
      run: az logout
      if: always()
