name: Frontend CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check frontend files
        run: ls -l frontend

      - name: Validate nginx.conf exists
        run: test -f frontend/nginx.conf && echo "nginx.conf found" || echo "nginx.conf missin
